<?php
define("DB_SERVER","localhost");
define("DB_NAME","checkin");
define("DB_USER","root");
define("DB_PASS","giveMePass");
define("PEAR_PATH","/usr/local/share/pear");
define("SERVER_URL","http://localhost/check");
define("SERVER_DIR","/Library/WebServer/Documents/check");
?>
