#!/bin/bash
printf "Step 2:To Create Empty Tables for the New Hotel,Enter the Database Name:\n"
read hotel
mysql -u root -p $hotel<<EOFMYSQL
CREATE TABLE IF NOT EXISTS admin (
uid int(11) AUTO_INCREMENT,
fname varchar(16),
lname varchar(16),
title varchar(6),
uaddress text,
email varchar(32),
password varchar(16),
lastlogin timestamp DEFAULT CURRENT_TIMESTAMP,
token varchar(16),
numlogin int(11) DEFAULT 0,
type int(1) DEFAULT 1,
PRIMARY KEY (uid),
UNIQUE KEY email(email)
);
CREATE TABLE IF NOT EXISTS booking (
id int(11) AUTO_INCREMENT,
rid varchar(11),
confirmation varchar(32),
hotelName varchar(128),
priceName varchar(32),
status varchar(16),
createDate varchar(12),
codeID varchar(128),
cid int(11),
currency varchar(5),
totalPrice float,
totalRoom int(3),
visitortax float,
totalVisitortax float,
origin varchar(256),
amountcc varchar(20),
autorisationcc varchar(32),
transactioncc varchar(256),
comment text,
roomnamelist varchar(256),
rememberprice varchar(256),
room1 varchar(32),
typeofbed1 varchar(32),
numberofadults1 int(3),
arrivalday1 int(2),
arrivalmonth1 int(2),
arrivalyear1 int(4),
arrivalhour1 int(2),
numberofdays1 int(2),
nonsmoking1 int(1),
numberofchildren1 int(2),
room2 varchar(32),
typeofbed2 varchar(32),
numberofadults2 int(3),
arrivalday2 int(2),
arrivalmonth2 int(2),
arrivalyear2 int(4),
arrivalhour2 int(2),
numberofdays2 int(2),
nonsmoking2 int(1),
numberofchildren2 int(2),
room3 varchar(32),
typeofbed3 varchar(32),
numberofadults3 int(3),
arrivalday3 int(2),
arrivalmonth3 int(3),
arrivalyear3 int(4),
arrivalhour3 int(2),
numberofdays3 int(2),
nonsmoking3 int(1),
numberofchildren3 int(2),
typeresa varchar(128),
extrafield varchar(128),
lastadminaccess timestamp DEFAULT CURRENT_TIMESTAMP,
email varchar(32),
hid int(1) DEFAULT 1,
step int(1) DEFAULT 0,
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS record (
rid varchar(11) ,
confirmation varchar(32) ,
hotelName varchar(128) ,
priceName varchar(32) ,
status varchar(16) ,
createDate varchar(12) ,
codeID varchar(128) ,
title varchar(6) ,
name varchar(64) ,
firstName varchar(32) ,
address varchar(256) ,
company varchar(256) ,
zip varchar(15) ,
city varchar(32) ,
country varchar(32) ,
state varchar(32) ,
email varchar(64) ,
tel varchar(24) ,
fax varchar(24) ,
currency varchar(5) ,
totalPrice float ,
totalRoom int(3) ,
visitortax float ,
totalVisitortax float ,
origin varchar(256) ,
amountcc varchar(20) ,
autorisationcc varchar(32) ,
transactioncc varchar(256) ,
comment text ,
roomnamelist varchar(256) ,
rememberprice varchar(256) ,
room1 varchar(32) ,
typeofbed1 varchar(32) ,
numberofadults1 int(3) ,
arrivalday1 int(2) ,
arrivalmonth1 int(2) ,
arrivalyear1 int(4) ,
nonsmoking1 int(1) ,
numberofchildren1 int(2) ,
room2 varchar(32) ,
typeofbed2 varchar(32) ,
numberofadults2 int(3) ,
arrivalday2 int(2) ,
arrivalmonth2 int(2) ,
arrivalyear2 int(4) ,
arrivalhour2 int(2) ,
arrivalhour1 int(2) ,
numberofdays2 int(2) ,
numberofdays1 int(2) ,
nonsmoking2 int(1) ,
numberofchildren2 int(2) ,
room3 varchar(32) ,
typeofbed3 varchar(32) ,
numberofadults3 int(3) ,
arrivalday3 int(2) ,
arrivalmonth3 int(3) ,
arrivalyear3 int(4) ,
arrivalhour3 int(2) ,
numberofdays3 int(2) ,
nonsmoking3 int(1) ,
numberofchildren3 int(2) ,
typeresa varchar(128) ,
extrafield varchar(128) ,
lastadminID int(11) ,
lastadminTime timestamp  DEFAULT CURRENT_TIMESTAMP,
importSource varchar(64) ,
uploadStatus varchar(11) ,
PRIMARY KEY (rid)
);
CREATE TABLE IF NOT EXISTS staff (
uid int(11)  AUTO_INCREMENT,
fname varchar(16) ,
lname varchar(16) ,
email varchar(32) ,
password varchar(32) ,
lastlogin timestamp  DEFAULT CURRENT_TIMESTAMP,
token varchar(32) ,
numlogin int(11)  DEFAULT 0,
PRIMARY KEY (uid),
UNIQUE KEY email (email)
);
CREATE TABLE IF NOT EXISTS upload(
upid int(11) AUTO_INCREMENT,
uid int(16),
fname varchar(128),
upload_time timestamp DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (upid)
);
CREATE TABLE IF NOT EXISTS user (
uid int(11)  AUTO_INCREMENT,
fname varchar(16) ,
lname varchar(16) ,
title varchar(6) ,
uaddress text ,
email varchar(32) ,
password varchar(16) ,
phone varchar(13) ,
passport varchar(16) ,
passportPhoto longtext ,
idPhoto longtext ,
lastlogin timestamp  DEFAULT CURRENT_TIMESTAMP,
token varchar(16) ,
numlogin int(11)  DEFAULT 0,
type int(1)  DEFAULT 1,
expireDate varchar(16) ,
issueDate varchar(16) ,
issueCountry varchar(64) ,
issueCity varchar(64) ,
PRIMARY KEY (uid),
UNIQUE KEY email (email),
UNIQUE KEY phone (phone)
);
CREATE TABLE IF NOT EXISTS hotel (
hid int(11)AUTO_INCREMENT,
hname varchar(32),
haddress varchar(128),
bannerUrl varchar(64),
message text,
imageUrl varchar(128),
tac text,
contact varchar(32),
step int(1) DEFAULT 1,
zip varchar(10),
PRIMARY KEY (hid)
);
EOFMYSQL

